name: Docker Image CI

on:
  release:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --tag benarmstrong/konichiiwa-node-api:latest
    - name: Login to Dockerhub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to Dockerhub
      run: docker push benarmstrong/konichiiwa-node-api:latest
    
